### PR TITLE
Correction of error message and documentation

### PR DESCRIPTION
**Pull request by TomRicci**
There were an issue with the error message when trying to add a server with `--protocol scpdown` or  `--protocol scpup` (instead of the correct `--protocol scpdownload` or  `--protocol scpupload`) : 
```
The protocol 'scpup' is not supported, expected either scpup, scpdown, sftp or rsync
```
Similarly the documentation was wrong on the correct syntaxe for those kind of calls.

### CODE REVIEW

**Comment by TomRicci** [comment]
Sorry about that, my browser didn't show the helpfull message in the check's result. I don't understand why the same check runing in a docker on my machine got errors on other files, though.

**Comment by speed47** [comment]
That's strange, because I can't seem to reproduce: I checked out your branch,  ran `./docker/devenv/run-tool.sh lint` on it, and only the oneline change in `ACL.pm` you've just done above was found.

The run-tool does spawn a docker with a precise version so that perlcritic/perltidy are under a given fixed version for everyone, to ensure we all get the same results. In this case, it's the version shipped with Ubuntu 20.04:

```
> docker exec -it the-bastion-devenv perltidy --version
This is perltidy, v20190601 
```

And not the `20220613` version you seem to have!

**Comment by TomRicci** [comment]
> The run-tool does spawn a docker with a precise version so that perlcritic/perltidy are under a given fixed version for everyone, to ensure we all get the same results. In this case, it's the version shipped with Ubuntu 20.04:
> 
> ```
> ./docker/devenv/run-tool.sh run perltidy --version
> This is perltidy, v20190601 
> ```
> 
> And not the `20220613` version you seem to have!

OK this make more sense to me now, I took a shortcut and directly ran the command `/opt/bastion/bin/dev/perl-tidy.sh test` in the docker I have on my machine (since docker inside docker doesn't seem to be a good idea ^^).

**Comment by speed47** [comment]
Note that the modifications you made in the tests were not really required, as the old parameters still work for backwards compatibility, hence why the tests did pass correctly. But we can keep it that way still :)

**Review by speed47 — APPROVED** [review]

**Comment by TomRicci** [comment]
Merci Stéphane !

**Pull request merged**
